### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [wphoong/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by wphoong** [comment]
I added the mobile meta tag, it should be better now.

**Comment by Mikeysax** [comment]
I don't see it in your application.html.erb: https://github.com/wphoong/splurty/blob/master/app/views/layouts/application.html.erb#L6

**Comment by wphoong** [comment]
Should be good now. I think there was an issue with my git push when i had changed it, so this time, I added the mobile media tag manually.

**Comment by Mikeysax** [comment]
Nice :+1:
